<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXl1iA5v\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXl1iA5v/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXl1iA5v.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXl1iA5v\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXl1iA5v\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xl1iA5v',
    'container.build_id' => '11c92bab',
    'container.build_time' => 1671035864,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXl1iA5v');
