<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXe75LMR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXe75LMR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXe75LMR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXe75LMR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXe75LMR\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xe75LMR',
    'container.build_id' => 'e3d769b5',
    'container.build_time' => 1680790547,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXe75LMR');
