<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYddZGTx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYddZGTx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYddZGTx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYddZGTx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYddZGTx\App_KernelDevDebugContainer([
    'container.build_hash' => 'YddZGTx',
    'container.build_id' => '32d9f6e9',
    'container.build_time' => 1784556521,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYddZGTx');
